### ISSUE TITLE
Pulled from CRAN

### ISSUE THREAD

**Issue by alexetalbott** [keberwein/blscrapeR#23]
It looks like this package has been removed from CRAN.

**Comment by keberwein** [comment]
Thanks for the report. It was pulled from CRAN because there are bad/old hyperlinks in the documentation. I was aware of the problem but haven't had tome to fix it yet. You can still do a devtools install if you need to use the package.

Again, thanks for the report!

`devtools::install_github("keberwein/blscrapeR")`

**Comment by keberwein** [comment]
We're back on CRAN now, thanks again for the heads-up!
