### ISSUE TITLE
NAICS/NIACS dataset title spelled incorrectly

### ISSUE THREAD

**Issue by wbk39** [keberwein/blscrapeR#28]
In your package, the dataset titled NIACS is spelled incorrectly. It should be NAICS. See here: https://www.census.gov/eos/www/naics/. Is it possible to fix this? Thank you!

**Comment by keberwein** [comment]
Thanks for bringing this to my attention. I will fix this ASAP and resubmit the package to CRAN this week. I will keep this issue open until the fixed repo has reached CRAN.

**Comment by wbk39** [comment]
Thank you so much for the quick response! I will keep an eye out for the updated package. I work with BLS data often so this is extremely helpful!

**Comment by keberwein** [comment]
No problem, glad you're getting good use out of the package. 

FYI, I'll keep the mis-spelled dataset on the next version (as not to disrupt other people's legacy code). I'll also add the correctly spelled NIACS data-set in parallel. This way, your current code won't be disrupted for another year or so...

When this issue is closed and the new version is on CRAN. Feel free to use either, but I will include a warning that the NAICAS dataset will be depreciated in the future.

**Comment by wbk39** [comment]
Thanks! So just to confirm, the incorrectly spelled NIACS dataset will be depreciated in the future and the correctly spelled NAICS one will function going forward?

**Comment by keberwein** [comment]
This has been resolved and is now a part of the new 3.2.0 version, which is on CRAN now.

https://github.com/keberwein/blscrapeR/commit/6f9a7c2a4340081ae682f4896f6a1efdac631234
