### ISSUE TITLE
inflation_adjust cannot return values before 1947

### ISSUE THREAD

**Issue by arthurgailes** [keberwein/blscrapeR#29]
```
> inflate = inflation_adjust(base_year = 1940)
trying URL 'https://download.bls.gov/pub/time.series/cu/cu.data.1.AllItems'
Content type 'text/plain' length unknown
downloaded 2.3 MB

Error in `$<-.data.frame`(`*tmp*`, "adj_value", value = numeric(0)) : 
  replacement has 0 rows, data has 73
```
Thanks for a wonderfully useful package.

**Comment by keberwein** [comment]
Thanks for the report. As it turns out there is a separate dataset needed for dates pre 1947. I added logic to the function to fall-back to that dataset when needed.

Turns out you caught me on the same week as a CRAN release, so the updated version (3.2.0) is on CRAN now.
https://github.com/keberwein/blscrapeR/commit/6f9a7c2a4340081ae682f4896f6a1efdac631234

**Comment by arthurgailes** [comment]
Wow, thank you!
