### ISSUE TITLE
Limits on series id?

### ISSUE THREAD

**Issue by cdeterman** [keberwein/blscrapeR#33]
I am trying to experiment with different series id values using the BLS documentation found [here](https://www.bls.gov/help/hlpforma.htm#SM).  I am particularly interested in the 'State and Area employment, hours, and earnings.  However, even the sample series id fails to pull with the following minor change.

example from BLS
```r
all_earnings <- bls_api(seriesid="SMU197802023800001",
                        startyear=2019)
```

However, if I modify the first two numeric values to 55 indicating Wisconsin as opposed to Iowa I just get the following indicating what seems to be success and failure.

```r
wis_earnings <- bls_api(seriesid="SMU557802023800001",
                        startyear=2019)
```

```
The API requires both a start and end year.
The endyear argument has automatically been set to 2021.
REQUEST_SUCCEEDED
Warning message:
Unknown or uninitialised column: `value`.
```

This results in a dataframe that is empty.  Any insight would be appreciated.

**Comment by cdeterman** [comment]
Furthermore, the SIC example series id fails, with the same results as above on its own, with the following from [here](https://www.bls.gov/help/hlpforma.htm#SIC).

```r
df <- bls_api(seriesid="SAS0800002000011", 
              startyear = 2019)
```

**Comment by keberwein** [comment]
The empty data frame is returned due to the code being malformated. In the first example we are looking for Employment statistics for Construction Workers in Des-Moins. That code is "SMU19197802023800001" the code you provided is missing two zeros, I assume you omitted the super-sector code. The BLS documentation you linked has the correct code.

The "[BLS Data Finder](https://beta.bls.gov/dataQuery/find?st=0&r=20&s=popularity%3AD&fq=survey:[sm]&fq=mg:[Measure+Category]&fq=mg:[Measure+Attributes]&fq=cg:[Industry]&fq=cg:[Geography]&fq=cc:[States+and+Territories]&fq=ccd:[Iowa]&fq=cc:[Construction]&fq=ccd:[All+Construction]&fq=cc:[Metropolitan+Statistical+Areas]&more=0&fq=ccd:[Des+Moines-West+Des+Moines+IA])" is a useful tool when trying to drill down to specific regions and occupations.

So, this works as expected.

`all_earnings <-  bls_api(seriesid="SMU19197802023800001", startyear=2019)`

**Comment by keberwein** [comment]
A high-priority ticket has been created to address this issue in the next version.
https://github.com/keberwein/blscrapeR/issues/35

**Comment by keberwein** [comment]
Other functionality that was added a while ago. There is a `series_id` function that will do a "fuzzy search" for certian things. Code below.

```
ids <- search_ids(keyword = c("Earnings", "Software", "Women"))
head(ids)
```
